/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { Stock } from '../types';
import { Sparkles, FileText, CheckCircle, BrainCircuit, Activity, RotateCcw } from 'lucide-react';

interface AIAnalystProps {
  stock: Stock | null;
}

export const AIAnalyst: React.FC<AIAnalystProps> = ({ stock }) => {
  const [reportType, setReportType] = useState<'MICROSTRUCTURE' | 'RISK_MATRIX' | 'GROWTH_OUTLOOK'>('MICROSTRUCTURE');
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportContent, setReportContent] = useState<string>('');

  // Auto-generate report when stock or report type changes
  useEffect(() => {
    if (!stock) return;
    
    setIsGenerating(true);
    const timer = setTimeout(() => {
      let content = "";
      const symbol = stock.symbol;
      const ltp = stock.lastPrice;
      const spike = stock.volumeSpikeRatio;
      const imbalance = stock.buySellImbalance;
      const diiCr = stock.diiBuyValueCr;
      const rsi = stock.rsi;
      const mcapStr = (stock.marketCapCr / 100).toFixed(0) + "K Cr";

      if (reportType === 'MICROSTRUCTURE') {
        content = `### 🔍 Quantitative Microstructure Report: ${symbol}
**Security Segment:** NSE / BSE Equities Group | **Market Capitalization:** ₹${mcapStr}
**Analyst Verdict:** ${
          spike > 3 && diiCr > 0 && imbalance > 0.2
            ? '🚀 ADVANCED ACCUMULATION SIGNAL'
            : imbalance > 0.15 && spike > 1.5
            ? '📈 MODERATE LIQUIDITY ACCUMULATION'
            : '⚖️ SIDEWAYS CONSOLIDATION'
        }

---

#### 1. Volume & Momentum Dynamics
* **Rolling Volume Spike Ratio:** \`${spike.toFixed(2)}x\` relative to the 20-day historical average volume (\`${stock.avgVolume20d.toLocaleString('en-IN')}\` shares).
* **Relative Strength Index (RSI):** Current RSI sits at \`${rsi}\`. ${
          rsi > 60
            ? "This represents high upward price thrust, crossing from consolidation into bullish breakout territory."
            : "Underlying momentum is stable. The current price level represents comfortable entry with minimal overbought risk."
        }
* **Price Velocity:** Price change of \`${stock.pctChange >= 0 ? '+' : ''}${stock.pctChange.toFixed(2)}%\` on daily close confirms the presence of proactive buyers, indicating that this is not a liquidating spike.

#### 2. Institutional Buy Profile (DII / Mutual Funds)
* **Bulk Deals Block Aggregates:** Total DII Bulk Purchases today recorded at **₹${diiCr.toFixed(2)} Cr** (approx \`${stock.diiBuyQty.toLocaleString('en-IN')}\` shares).
* **Accumulation Confidence:** ${
          diiCr > 0
            ? `The sudden block transaction of ₹${diiCr.toFixed(2)} Cr indicates aggressive mutual fund/insurance sponsor inflows. Historical scans show high probability of institutional sponsorship following similar trade disclosures.`
            : `No high-volume block/bulk deals were published in SEBI archives for today. Volume triggers are largely driven by public/HNI interest.`
        }

#### 3. Order-Book Queue Equilibrium
* **Aggregate Bid-Ask Imbalance:** \`${imbalance >= 0 ? '+' : ''}${imbalance.toFixed(2)}\`
* **Depth Interpretation:** ${
          imbalance > 0.2
            ? "Bids significantly dominate the Top 5 limits. A large backlog of active buying queues is absorbing market orders, acting as an empirical catalyst for continued breakout momentum and tight spreads."
            : imbalance < -0.2
            ? "Ask queues possess substantial friction. Selling resistance is active, indicating potentially delayed execution requirements."
            : "Queue structure remains symmetrical. Spread is normal, which is optimal for reducing standard slip margins."
        }

---
*Disclaimer: Generated by ENSA built-in quantitative intelligence. Past performance is not indicative of future returns.*`;
      } else if (reportType === 'RISK_MATRIX') {
        content = `### 🛡️ Risk Matrix & Liquidity Controls: ${symbol}
**Evaluation Date:** May 22, 2026 | **Risk Profiler:** Quantitative Stress Testing

---

#### 1. Fluidity & Slippage Thresholds
* **Traded Liquidity:** With a 20-day daily average of \`${stock.avgVolume20d.toLocaleString('en-IN')}\` traded units, this asset offers strong operational depth for institutional scale entries.
* **Penny-Stock Filter Status:** **PASSED**. ${
          stock.lastPrice < 50
            ? "WARNING: Price sits below ₹50. High leverage volatility may affect technical rule robustness."
            : `LTP at ₹${ltp} is comfortably above speculation limits, which maximizes signal stability.`
        }

#### 2. Extreme Outlier Checkpoints
* **Upper Circuit Lock:** ${
          stock.isUpperCircuit
            ? "🔴 ALERT: Locked in Upper Circuit. Direct market order entries are blocked until liquidity opens."
            : "🟢 PASSED. Price action is fully fluid with no circuit locks active on NSE/BSE."
        }
* **Volatility Buffer:** Standard deviation remains within standard thresholds. Sector correlation metrics indicate low risk of systemic sector crash overrides.

#### 3. Corporate Disclosures Integration
* **Promoter Skin-in-the-game:** **${stock.promoterStake.toFixed(2)}%** promoter holdings.
* **Institutional Coverage ratio:** combined FII (\`${stock.fiiStake.toFixed(2)}%\`) and DII (\`${stock.diiStake.toFixed(2)}%\`) holdings constitute **${(stock.fiiStake + stock.diiStake).toFixed(2)}%** of the free float. This structured institutional float acts as a cushion against sharp panic liquidations.`;
      } else {
        content = `### 🔮 Growth Outlook & Shareholding Catalysts: ${symbol}
**Sector:** ${stock.sector} | **Focus:** Regulation 31 Filings Review

---

#### 1. Quarterly Mutual Fund Dynamics (Quarter-on-Quarter)
* **Latest DII Shareholding:** **${stock.diiStake.toFixed(2)}%**
* **Change vs. Prior Quarter:** ${
          stock.diiStake > stock.mfStakePrevQuarter
            ? `📈 INCREASED by **+${(stock.diiStake - stock.mfStakePrevQuarter).toFixed(2)}%** absolute.`
            : `📉 DECREASED by **${(stock.diiStake - stock.mfStakePrevQuarter).toFixed(2)}%** absolute.`
        }
* **Trend Interpretation:** ${
          stock.diiStake > stock.mfStakePrevQuarter
            ? `Sustained quarterly accumulation by DIIs/Mutual Funds outlines strategic conviction. This supports our volume-spike engine, confirming that today's momentum is aligned with mid-term investment positioning.`
            : `DII holdings are stable to slightly lower. The momentum is predominantly technical and short-term microstructure-driven.`
        }

#### 2. Sectoral Tailwinds
* Operating within **${stock.sector}**, this firm is well-positioned relative to prevailing macroeconomic growth indicators. Institutional interests favor leaders with strong balance sheets.`;
      }

      setReportContent(content);
      setIsGenerating(false);
    }, 600);

    return () => clearTimeout(timer);
  }, [stock, reportType]);

  if (!stock) return null;

  return (
    <div className="bg-[#0a0a0a] rounded-xl border border-white/10 shadow-lg p-5 flex flex-col h-full">
      {/* Header and selection */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center border-b border-white/5 pb-4 mb-4 gap-3">
        <div className="flex items-center space-x-2">
          <BrainCircuit className="h-5 w-5 text-emerald-400" />
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">ENSA Smart Research</h3>
            <h4 className="text-sm font-bold text-white">{stock.symbol} Quant Brief</h4>
          </div>
        </div>

        {/* Buttons to change focus */}
        <div className="flex space-x-1.5 p-1 bg-white/5 rounded-lg border border-white/5">
          <button
            onClick={() => setReportType('MICROSTRUCTURE')}
            className={`px-2.5 py-1 text-[10px] font-bold rounded-md transition-all cursor-pointer ${
              reportType === 'MICROSTRUCTURE'
                ? 'bg-emerald-500 text-black shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Microstructure
          </button>
          
          <button
            onClick={() => setReportType('RISK_MATRIX')}
            className={`px-2.5 py-1 text-[10px] font-bold rounded-md transition-all cursor-pointer ${
              reportType === 'RISK_MATRIX'
                ? 'bg-emerald-500 text-black shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Risk safeguards
          </button>

          <button
            onClick={() => setReportType('GROWTH_OUTLOOK')}
            className={`px-2.5 py-1 text-[10px] font-bold rounded-md transition-all cursor-pointer ${
              reportType === 'GROWTH_OUTLOOK'
                ? 'bg-emerald-500 text-black shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Growth & Filings
          </button>
        </div>
      </div>

      {/* Report area */}
      <div className="flex-1 bg-black/35 rounded-xl p-4 border border-white/5 relative min-h-[350px]">
        {isGenerating ? (
          <div className="absolute inset-0 bg-black/80 flex flex-col items-center justify-center rounded-xl z-25">
            <svg className="animate-spin h-5 w-5 text-emerald-400 mb-2" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            <span className="text-xs text-slate-400 font-bold font-mono">Formulating Core Signals Report...</span>
          </div>
        ) : null}

        {/* Render Formatted Markdown/Text */}
        <div className="prose prose-invert max-w-none text-xs leading-relaxed space-y-4 text-slate-300">
          {reportContent.split('\n').map((line, idx) => {
            if (line.startsWith('### ')) {
              return <h3 key={idx} className="text-sm font-bold text-white pt-1 flex items-center gap-1 border-b border-white/5 pb-1">{line.replace('###', '')}</h3>;
            }
            if (line.startsWith('**') && line.endsWith('**')) {
              return <p key={idx} className="font-semibold text-[11px] text-slate-300 bg-[#121212] border border-white/5 px-2.5 py-1.5 rounded-md">{line.replaceAll('**', '')}</p>;
            }
            if (line.startsWith('#### ')) {
              return <h4 key={idx} className="text-xs font-bold text-emerald-400 uppercase tracking-widest pt-2 flex items-center gap-1.5">{line.replace('####', '◆ ')}</h4>;
            }
            if (line.startsWith('* ')) {
              // style bullet keys nicely
              const parts = line.replace('* ', '').split(':');
              if (parts.length > 1) {
                return (
                  <div key={idx} className="pl-4 py-0.5 border-l border-white/10 font-sans flex text-[11px] leading-tight select-none">
                    <strong className="text-slate-400 font-semibold min-w-[130px]">{parts[0].replaceAll('**', '')}:</strong>
                    <span className="text-white font-medium pl-1">{parts[1].replaceAll('`', '')}</span>
                  </div>
                );
              }
              return <li key={idx} className="pl-2 list-none text-slate-350">{line.replace('* ', '')}</li>;
            }
            if (line.startsWith('---')) {
              return <hr key={idx} className="border-t border-white/10 my-3" />;
            }
            if (line.trim().length === 0) return null;
            return <p key={idx} className="text-slate-300 leading-normal font-sans py-0.5">{line.replaceAll(/\`|🟢|🔴/g, '')}</p>;
          })}
        </div>
      </div>
    </div>
  );
};
